name: ATC Log 
description: Create Daily ATC Log Issue
title: "[ATC Log]: 202Y-MM-DD"
labels: ["atc"]
body:
- type: textarea
  attributes:
    label: "ATC:" 
    description: Your GitHub handle 
- type: textarea
  attributes:
    label: The Log
    value: |
      "## What was worked on"
      <!-- Issues and problems that happened during -->
      "## Issues Triaged"
      <!-- Links to issues created during the atc shift -->
      "## Recurring Issues"
      <!-- Links to recurring problems -->
      "## Timeline (Eastern Time)"
      <!-- Log all important events like productions incidents or issue with the merge queue. -->
    render: markdown
  validations:
    required: false
